name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: install pnpm
      uses: actions/setup-node@v3
        with:
          node-version: '19' # Specify the Node.js version
          cache: 'pnpm' # Enable caching for pnpm
          
    - name: Build
      run: |
        npm install pnpm
        pnpm install
        npx webpack
